'use client';

import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Target, CheckCircle, XCircle, Sparkles, Lock, Lightbulb, BarChart3, Rocket, ClipboardCopy, Download, Zap, X, FileText, History, ChevronDown } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Button } from '@/components/ui/Button';
import { LoadingSpinner } from '@/components/ui/Loading';
import { useToast } from '@/components/ui/Toast';

interface SavedPackage {
    id: string;
    content: string;
    decisions_count: number;
    created_at: string;
}

interface PromotionPackageGeneratorProps {
    decisionCount: number;
}

export function PromotionPackageGenerator({ decisionCount }: PromotionPackageGeneratorProps) {
    const [showModal, setShowModal] = useState(false);
    const [generating, setGenerating] = useState(false);
    const [generatedPackage, setGeneratedPackage] = useState<string | null>(null);
    const [error, setError] = useState('');
    const [savedPackages, setSavedPackages] = useState<SavedPackage[]>([]);
    const [loadingSaved, setLoadingSaved] = useState(false);
    const [showHistory, setShowHistory] = useState(false);
    const { showToast } = useToast();
    const printRef = useRef<HTMLDivElement>(null);

    // Fetch saved packages when modal opens
    useEffect(() => {
        if (showModal) {
            fetchSavedPackages();
        }
    }, [showModal]);

    const fetchSavedPackages = async () => {
        setLoadingSaved(true);
        try {
            const response = await fetch('/api/promotion-packages');
            const data = await response.json();
            if (response.ok) {
                setSavedPackages(data.packages || []);
            }
        } catch (err) {
            console.error('Failed to fetch saved packages:', err);
        } finally {
            setLoadingSaved(false);
        }
    };

    const handleGenerate = async () => {
        setGenerating(true);
        setError('');
        setShowHistory(false);

        try {
            const session = await fetch('/api/auth/session').then(r => r.json());
            const response = await fetch('/api/ai/promotion-package', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${session.access_token}`,
                },
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Failed to generate package');
            }

            setGeneratedPackage(data.package);
            // Refresh saved packages list
            fetchSavedPackages();
        } catch (err) {
            const message = err instanceof Error ? err.message : 'Failed to generate package';
            setError(message);
        } finally {
            setGenerating(false);
        }
    };

    const handleCopy = () => {
        if (generatedPackage) {
            navigator.clipboard.writeText(generatedPackage);
            showToast('Copied to clipboard!', 'success');
        }
    };

    const handleDownloadMarkdown = () => {
        if (generatedPackage) {
            const blob = new Blob([generatedPackage], { type: 'text/markdown' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `promotion-package-${new Date().toISOString().split('T')[0]}.md`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            showToast('Downloaded Markdown file!', 'success');
        }
    };

    const handleDownloadPDF = async () => {
        if (generatedPackage) {
            showToast('Generating PDF...', 'info');

            try {
                // Dynamically import jsPDF to avoid SSR issues
                const { jsPDF } = await import('jspdf');

                const doc = new jsPDF({
                    orientation: 'portrait',
                    unit: 'mm',
                    format: 'a4'
                });

                // Set up fonts and colors
                const pageWidth = doc.internal.pageSize.getWidth();
                const pageHeight = doc.internal.pageSize.getHeight();
                const margin = 20;
                const maxWidth = pageWidth - (margin * 2);
                let yPosition = margin;

                // Header
                doc.setFontSize(22);
                doc.setTextColor(15, 23, 42); // slate-900
                doc.text('Professional Self-Review', pageWidth / 2, yPosition, { align: 'center' });
                yPosition += 8;

                // Date
                doc.setFontSize(11);
                doc.setTextColor(100, 116, 139); // slate-500
                const dateStr = `Generated by Career Black Box • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
                doc.text(dateStr, pageWidth / 2, yPosition, { align: 'center' });
                yPosition += 5;

                // Header line
                doc.setDrawColor(99, 102, 241); // indigo-500
                doc.setLineWidth(0.5);
                doc.line(margin, yPosition, pageWidth - margin, yPosition);
                yPosition += 12;

                // Process markdown content - convert to plain text with formatting
                const lines = generatedPackage.split('\n');

                for (const line of lines) {
                    // Check if we need a new page
                    if (yPosition > pageHeight - 30) {
                        doc.addPage();
                        yPosition = margin;
                    }

                    const trimmedLine = line.trim();

                    // Skip empty lines but add some spacing
                    if (!trimmedLine) {
                        yPosition += 4;
                        continue;
                    }

                    // Handle headers
                    if (trimmedLine.startsWith('### ')) {
                        yPosition += 4;
                        doc.setFontSize(13);
                        doc.setTextColor(51, 65, 85); // slate-700
                        const text = trimmedLine.replace('### ', '');
                        const splitText = doc.splitTextToSize(text, maxWidth);
                        doc.text(splitText, margin, yPosition);
                        yPosition += splitText.length * 6 + 2;
                    } else if (trimmedLine.startsWith('## ')) {
                        yPosition += 6;
                        doc.setFontSize(15);
                        doc.setTextColor(30, 41, 59); // slate-800
                        const text = trimmedLine.replace('## ', '');
                        const splitText = doc.splitTextToSize(text, maxWidth);
                        doc.text(splitText, margin, yPosition);
                        yPosition += splitText.length * 7 + 4;
                        // Add underline
                        doc.setDrawColor(226, 232, 240); // slate-200
                        doc.setLineWidth(0.3);
                        doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
                    } else if (trimmedLine.startsWith('# ')) {
                        yPosition += 8;
                        doc.setFontSize(18);
                        doc.setTextColor(15, 23, 42); // slate-900
                        const text = trimmedLine.replace('# ', '');
                        const splitText = doc.splitTextToSize(text, maxWidth);
                        doc.text(splitText, margin, yPosition);
                        yPosition += splitText.length * 8 + 4;
                    } else if (trimmedLine.startsWith('* ') || trimmedLine.startsWith('- ')) {
                        // List items
                        doc.setFontSize(11);
                        doc.setTextColor(71, 85, 105); // slate-600
                        const text = '• ' + trimmedLine.substring(2).replace(/\*\*/g, '').replace(/\*/g, '');
                        const splitText = doc.splitTextToSize(text, maxWidth - 5);
                        doc.text(splitText, margin + 5, yPosition);
                        yPosition += splitText.length * 5 + 1;
                    } else if (trimmedLine.startsWith('---')) {
                        // Horizontal rule
                        yPosition += 4;
                        doc.setDrawColor(226, 232, 240);
                        doc.setLineWidth(0.2);
                        doc.line(margin, yPosition, pageWidth - margin, yPosition);
                        yPosition += 6;
                    } else {
                        // Regular paragraph
                        doc.setFontSize(11);
                        doc.setTextColor(71, 85, 105); // slate-600
                        // Remove markdown formatting
                        const text = trimmedLine.replace(/\*\*/g, '').replace(/\*/g, '').replace(/`/g, '');
                        const splitText = doc.splitTextToSize(text, maxWidth);
                        doc.text(splitText, margin, yPosition);
                        yPosition += splitText.length * 5 + 2;
                    }
                }

                // Footer
                const footerY = pageHeight - 15;
                doc.setFontSize(9);
                doc.setTextColor(148, 163, 184); // slate-400
                doc.setDrawColor(226, 232, 240);
                doc.setLineWidth(0.2);
                doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
                doc.text('Generated by Career Black Box - Your Professional Flight Recorder', pageWidth / 2, footerY, { align: 'center' });

                // Save the PDF
                doc.save(`promotion-package-${new Date().toISOString().split('T')[0]}.pdf`);
                showToast('PDF downloaded successfully!', 'success');
            } catch (err) {
                console.error('PDF generation error:', err);
                showToast('Failed to generate PDF. Try copying as markdown instead.', 'error');
            }
        }
    };

    const canGenerate = decisionCount >= 3;

    return (
        <>
            <motion.div
                whileHover={{ scale: 1.01 }}
                className="bg-gradient-to-r from-indigo-600 to-violet-600 rounded-xl p-6 text-white shadow-lg border border-white/5"
            >
                <div className="flex items-start justify-between">
                    <div className="flex-1">
                        <h3 className="text-2xl font-bold mb-2 font-outfit flex items-center gap-2">
                            <Target className="w-6 h-6" /> AI Promotion Package
                        </h3>
                        <p className="text-indigo-100 mb-4">
                            Generate a professional self-review document showcasing your decision-making quality.
                        </p>
                        <div className="flex items-center gap-4 mb-4">
                            <div className="bg-white/20 rounded-lg px-4 py-2">
                                <div className="text-sm text-indigo-100">Your Decisions</div>
                                <div className="text-2xl font-bold">{decisionCount}</div>
                            </div>
                            <div className="text-sm text-indigo-100 flex items-center gap-2">
                                {canGenerate ? (
                                    <>
                                        <CheckCircle className="w-4 h-4 text-emerald-300" />
                                        Ready to generate
                                    </>
                                ) : (
                                    <>
                                        <XCircle className="w-4 h-4 text-red-300" />
                                        Need {3 - decisionCount} more decisions
                                    </>
                                )}
                            </div>
                        </div>
                    </div>
                </div>

                <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                    <Button
                        onClick={() => setShowModal(true)}
                        disabled={!canGenerate}
                        variant="primary"
                        size="lg"
                        className="bg-white text-indigo-600 hover:bg-slate-100 border-0 shadow-lg"
                    >
                        {canGenerate ? (
                            <>
                                <Sparkles className="w-4 h-4 mr-2" /> Generate Promotion Package
                            </>
                        ) : (
                            <>
                                <Lock className="w-4 h-4 mr-2" /> Need 3+ Decisions
                            </>
                        )}
                    </Button>
                </motion.div>

                <p className="text-xs text-indigo-200 mt-3 flex items-center gap-1">
                    <Lightbulb className="w-3 h-3" /> Free while in beta. Normally ₹500 per generation.
                </p>
            </motion.div>

            {/* Modal */}
            <AnimatePresence>
                {showModal && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4"
                    >
                        <motion.div
                            initial={{ scale: 0.95, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            exit={{ scale: 0.95, opacity: 0 }}
                            className="bg-slate-900 border border-white/10 rounded-xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col shadow-2xl"
                        >
                            {/* Modal Header */}
                            <div className="p-6 border-b border-white/10">
                                <div className="flex items-center justify-between">
                                    <h3 className="text-2xl font-bold text-white font-outfit flex items-center gap-2">
                                        {generatedPackage ? (
                                            <>
                                                <CheckCircle className="w-6 h-6 text-emerald-400" /> Your Promotion Package
                                            </>
                                        ) : (
                                            <>
                                                <Zap className="w-6 h-6 text-amber-400" /> Generate Promotion Package
                                            </>
                                        )}
                                    </h3>
                                    <button
                                        onClick={() => {
                                            setShowModal(false);
                                            setGeneratedPackage(null);
                                            setError('');
                                        }}
                                        className="text-slate-400 hover:text-white p-2 hover:bg-white/5 rounded-lg transition-colors"
                                        aria-label="Close modal"
                                    >
                                        <X className="w-6 h-6" />
                                    </button>
                                </div>
                            </div>

                            {/* Modal Content */}
                            <div className="flex-1 overflow-y-auto p-6">
                                {!generatedPackage && !generating && (
                                    <div className="space-y-4">
                                        <div className="bg-indigo-500/10 border border-indigo-500/20 rounded-lg p-4">
                                            <h4 className="font-semibold text-indigo-300 mb-2">What You'll Get:</h4>
                                            <ul className="space-y-2 text-sm text-indigo-200">
                                                <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-400" /> Executive summary of your decision-making quality</li>
                                                <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-400" /> Pattern analysis backed by specific examples</li>
                                                <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-400" /> Growth trajectory over time</li>
                                                <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-400" /> Impact & outcomes from your decisions</li>
                                                <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-400" /> Risk management assessment</li>
                                                <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-400" /> Professional format ready for performance reviews</li>
                                            </ul>
                                        </div>

                                        <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
                                            <h4 className="font-semibold text-green-300 mb-2 flex items-center gap-2">
                                                <BarChart3 className="w-4 h-4" /> Your Data:
                                            </h4>
                                            <p className="text-sm text-green-200">
                                                Analyzing <strong>{decisionCount} decisions</strong> from your Career Black Box
                                            </p>
                                        </div>

                                        {error && (
                                            <motion.div
                                                initial={{ opacity: 0, y: -10 }}
                                                animate={{ opacity: 1, y: 0 }}
                                                className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-lg text-sm"
                                            >
                                                {error}
                                            </motion.div>
                                        )}

                                        <motion.div whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                                            <Button
                                                onClick={handleGenerate}
                                                disabled={generating}
                                                variant="primary"
                                                size="lg"
                                                className="w-full"
                                            >
                                                <Rocket className="w-4 h-4 mr-2" /> Generate Now (Free)
                                            </Button>
                                        </motion.div>

                                        {/* Saved Packages History */}
                                        {savedPackages.length > 0 && (
                                            <div className="mt-6 border-t border-white/10 pt-4">
                                                <button
                                                    onClick={() => setShowHistory(!showHistory)}
                                                    className="flex items-center justify-between w-full text-left text-slate-300 hover:text-white transition-colors"
                                                >
                                                    <span className="flex items-center gap-2 font-medium">
                                                        <History className="w-4 h-4" />
                                                        Previous Packages ({savedPackages.length})
                                                    </span>
                                                    <ChevronDown className={`w-4 h-4 transition-transform ${showHistory ? 'rotate-180' : ''}`} />
                                                </button>

                                                <AnimatePresence>
                                                    {showHistory && (
                                                        <motion.div
                                                            initial={{ height: 0, opacity: 0 }}
                                                            animate={{ height: 'auto', opacity: 1 }}
                                                            exit={{ height: 0, opacity: 0 }}
                                                            className="overflow-hidden"
                                                        >
                                                            <div className="mt-3 space-y-2 max-h-48 overflow-y-auto">
                                                                {savedPackages.map((pkg) => (
                                                                    <button
                                                                        key={pkg.id}
                                                                        onClick={() => {
                                                                            setGeneratedPackage(pkg.content);
                                                                            setShowHistory(false);
                                                                        }}
                                                                        className="w-full flex items-center justify-between bg-slate-800/50 hover:bg-slate-700/50 border border-white/5 rounded-lg px-4 py-3 text-left transition-colors"
                                                                    >
                                                                        <div>
                                                                            <p className="text-sm text-white font-medium">
                                                                                {new Date(pkg.created_at).toLocaleDateString('en-US', {
                                                                                    year: 'numeric',
                                                                                    month: 'short',
                                                                                    day: 'numeric',
                                                                                })}
                                                                            </p>
                                                                            <p className="text-xs text-slate-400">
                                                                                {pkg.decisions_count} decisions analyzed
                                                                            </p>
                                                                        </div>
                                                                        <FileText className="w-4 h-4 text-slate-400" />
                                                                    </button>
                                                                ))}
                                                            </div>
                                                        </motion.div>
                                                    )}
                                                </AnimatePresence>
                                            </div>
                                        )}

                                        {loadingSaved && (
                                            <div className="mt-4 flex justify-center">
                                                <LoadingSpinner size="sm" />
                                            </div>
                                        )}
                                    </div>
                                )}

                                {generating && (
                                    <div className="text-center py-12">
                                        <LoadingSpinner size="lg" />
                                        <p className="mt-4 text-slate-300 font-medium">
                                            AI is analyzing your {decisionCount} decisions...
                                        </p>
                                        <p className="text-sm text-slate-500 mt-2">
                                            This may take 15-30 seconds
                                        </p>
                                    </div>
                                )}

                                {generatedPackage && (
                                    <div className="space-y-4">
                                        {/* GitHub-style markdown preview */}
                                        <div
                                            ref={printRef}
                                            className="bg-slate-800/50 border border-white/5 rounded-lg p-6 max-h-[400px] overflow-y-auto prose prose-invert prose-sm max-w-none
                                                prose-headings:font-outfit prose-headings:text-white
                                                prose-h1:text-2xl prose-h1:border-b prose-h1:border-indigo-500/50 prose-h1:pb-2 prose-h1:mb-4
                                                prose-h2:text-xl prose-h2:border-b prose-h2:border-white/10 prose-h2:pb-2 prose-h2:mt-6
                                                prose-h3:text-lg prose-h3:text-slate-200 prose-h3:mt-4
                                                prose-h4:text-base prose-h4:text-slate-300
                                                prose-p:text-slate-300 prose-p:leading-relaxed
                                                prose-strong:text-white prose-strong:font-semibold
                                                prose-em:text-slate-300
                                                prose-ul:text-slate-300 prose-ol:text-slate-300
                                                prose-li:my-1 prose-li:marker:text-indigo-400
                                                prose-blockquote:border-l-indigo-500 prose-blockquote:bg-indigo-500/10 prose-blockquote:not-italic
                                                prose-code:bg-slate-700 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-indigo-300
                                                prose-pre:bg-slate-800 prose-pre:border prose-pre:border-white/5
                                                prose-hr:border-white/10
                                                prose-table:border prose-table:border-white/10
                                                prose-th:bg-slate-800 prose-th:border prose-th:border-white/10 prose-th:px-3 prose-th:py-2
                                                prose-td:border prose-td:border-white/10 prose-td:px-3 prose-td:py-2
                                            "
                                        >
                                            <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                                {generatedPackage}
                                            </ReactMarkdown>
                                        </div>

                                        {/* Action Buttons */}
                                        <div className="flex flex-wrap gap-3">
                                            <motion.div className="flex-1 min-w-[140px]" whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                                                <Button
                                                    onClick={handleCopy}
                                                    variant="secondary"
                                                    size="lg"
                                                    className="w-full"
                                                >
                                                    <ClipboardCopy className="w-4 h-4 mr-2" /> Copy
                                                </Button>
                                            </motion.div>
                                            <motion.div className="flex-1 min-w-[140px]" whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                                                <Button
                                                    onClick={handleDownloadMarkdown}
                                                    variant="outline"
                                                    size="lg"
                                                    className="w-full border-white/10 text-slate-300 hover:bg-white/5"
                                                >
                                                    <FileText className="w-4 h-4 mr-2" /> .md
                                                </Button>
                                            </motion.div>
                                            <motion.div className="flex-1 min-w-[140px]" whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                                                <Button
                                                    onClick={handleDownloadPDF}
                                                    variant="primary"
                                                    size="lg"
                                                    className="w-full"
                                                >
                                                    <Download className="w-4 h-4 mr-2" /> PDF
                                                </Button>
                                            </motion.div>
                                        </div>

                                        <p className="text-xs text-slate-500 text-center">
                                            💡 Tip: Use Ctrl+P or the PDF button to save as PDF with professional formatting
                                        </p>
                                    </div>
                                )}
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </>
    );
}

